# CATHODE 模型配置
# 参考原始仓库的 CATHODE_8.yml

ModelType: 'MAF'
Transform: 'Affine'
optimizer: 'Adam'
num_cond_inputs: 1
num_layers: 1
num_blocks: 6
num_hidden: 20
activation_function: 'tanh'
pre_exp_tanh: false
batch_norm: true
batch_norm_momentum: 1

optimizer:
  name: Adam
  lr: 0.00075
  weight_decay: 0.000001

